// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    bakery_orders: {
        name: "bakery_orders";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          order_id: string;
          /** @sqlType STRING */
          customer_name: string;
          /** @sqlType STRING */
          items: string;
          /** @sqlType INT */
          quantity: number;
          /** @sqlType DECIMAL(10,2) */
          order_total: number;
          /** @sqlType TIMESTAMP */
          due_at: string;
          /** @sqlType BOOLEAN */
          packed: boolean;
          /** @sqlType BOOLEAN */
          needs_attention: boolean;
        }>;
      };
  }
}
