"""Edge harvest of the session's residue (contract C6, tier 3).

The harvester's value is entirely in what it leaves behind. These tests are
weighted accordingly: the exclusions (file contents, stdout, stack-trace bodies)
get as much attention as the inclusions, because a harvester that quietly starts
shipping tool output turns an opt-in sales feature into a transcript exfiltrator.

The second theme is tolerance. Two agent harnesses write these logs, both change
their envelope between releases, and a parser pinned to one shape fails by
extracting nothing — which is indistinguishable from an attendee who said nothing.
"""

from __future__ import annotations

import json
import os
import subprocess

import pytest

from server import artifacts
from server.artifacts import Artifact, Harvest, harvest_user

from . import synthetic_secrets as fake


class _User:
    """The two attributes the harvester actually reads."""

    def __init__(self, home: str, email: str = "alice@example.com"):
        self.home = home
        self.email = email


@pytest.fixture
def home(tmp_path):
    path = tmp_path / "home"
    (path / ".claude" / "projects" / "p").mkdir(parents=True)
    return path


def _write_transcript(home, entries, name: str = "session.jsonl") -> str:
    path = home / ".claude" / "projects" / "p" / name
    path.write_text("\n".join(json.dumps(e) for e in entries) + "\n")
    return str(path)


def _claude_user(text) -> dict:
    return {"type": "user", "message": {"role": "user", "content": text}}


def _claude_tool(name: str, tool_input: dict) -> dict:
    return {
        "type": "assistant",
        "message": {
            "role": "assistant",
            "content": [{"type": "tool_use", "name": name, "input": tool_input}],
        },
    }


# --- Attendee prompts ---------------------------------------------------------


def test_attendee_prompts_are_captured_verbatim(home):
    _write_transcript(
        home,
        [_claude_user("How do I connect this to our Confluent Kafka cluster?")],
    )
    result = harvest_user(_User(str(home)))

    assert result.prompts == ["How do I connect this to our Confluent Kafka cluster?"]
    assert result.prompt_count == 1


def test_both_string_and_block_content_shapes_are_read(home):
    """Claude sends either, depending on how the turn was composed."""
    _write_transcript(
        home,
        [
            _claude_user("plain string turn"),
            _claude_user([{"type": "text", "text": "block turn"}]),
        ],
    )
    result = harvest_user(_User(str(home)))

    assert result.prompts == ["plain string turn", "block turn"]


def test_a_codex_style_envelope_is_read_too(home):
    """A parser pinned to one harness silently drops the other's whole session."""
    path = home / ".codex" / "sessions" / "2026"
    path.mkdir(parents=True)
    (path / "rollout.jsonl").write_text(
        json.dumps(
            {
                "type": "response_item",
                "payload": {
                    "role": "user",
                    "content": [
                        {"type": "input_text", "text": "migrate our Oracle CDC job"}
                    ],
                },
            }
        )
        + "\n"
    )
    result = harvest_user(_User(str(home)))

    assert result.prompts == ["migrate our Oracle CDC job"]


def test_tool_results_never_become_prompts(home):
    """Tool output arrives on the user role and is the bulk of a transcript."""
    _write_transcript(
        home,
        [
            _claude_user(
                [
                    {
                        "type": "tool_result",
                        "content": "row1,row2,row3\nrow4,row5\n... 40k more rows",
                    }
                ]
            ),
            _claude_user("why is the join so slow?"),
        ],
    )
    result = harvest_user(_User(str(home)))

    assert result.prompts == ["why is the join so slow?"]
    assert not any("row1" in p for p in result.prompts)


def test_harness_injected_pseudo_turns_are_dropped(home):
    """Nobody typed these, and a brief must not quote the harness to a customer."""
    _write_transcript(
        home,
        [
            _claude_user("<command-name>/clear</command-name>"),
            _claude_user("<system-reminder>Your context is running low</system-reminder>"),
            _claude_user("Caveat: The messages below were generated by a hook"),
            _claude_user("[Request interrupted by user]"),
            _claude_user("build me a streaming pipeline"),
        ],
    )
    result = harvest_user(_User(str(home)))

    assert result.prompts == ["build me a streaming pipeline"]
    assert result.prompt_count == 1, "synthetic turns must not inflate engagement"


def test_continuations_are_counted_but_not_summarised(home):
    """"yes" means nothing standalone, but forty of them describe the session.

    Dropping them from the count would understate a highly engaged attendee;
    feeding them to the summariser would spend the context window on noise.
    """
    _write_transcript(
        home,
        [
            _claude_user("build a genie space over our sales data"),
            _claude_user("yes"),
            _claude_user("go ahead"),
            _claude_user("Fix that"),
        ],
    )
    result = harvest_user(_User(str(home)))

    assert result.prompts == ["build a genie space over our sales data"]
    assert result.prompt_count == 4


def test_prompts_are_redacted(home):
    _write_transcript(
        home,
        [_claude_user(f"connect using token {fake.DAPI_TOKEN}")],
    )
    result = harvest_user(_User(str(home)))

    assert fake.DAPI_TOKEN not in result.prompts[0]
    assert result.redactions == 1


def test_prompt_capture_is_bounded(home):
    _write_transcript(
        home,
        [_claude_user(f"question number {i} about lakebase") for i in range(400)],
    )
    result = harvest_user(_User(str(home)))

    assert len(result.prompts) == artifacts.MAX_PROMPTS
    # The count is not capped: it is the cheap engagement signal.
    assert result.prompt_count == 400


def test_an_oversized_prompt_is_truncated(home):
    _write_transcript(home, [_claude_user("x" * 5000)])
    result = harvest_user(_User(str(home)))

    assert len(result.prompts[0]) == artifacts.MAX_PROMPT_CHARS


# --- Plans, tool targets, errors ----------------------------------------------


def test_todo_blocks_capture_the_agents_read_of_intent(home):
    _write_transcript(
        home,
        [
            _claude_tool(
                "TodoWrite",
                {
                    "todos": [
                        {"content": "Ingest the Kafka topic into a bronze table"},
                        {"content": "Add a DLT expectation on the payment amount"},
                    ]
                },
            )
        ],
    )
    result = harvest_user(_User(str(home)))

    assert result.plans == [
        "Ingest the Kafka topic into a bronze table",
        "Add a DLT expectation on the payment amount",
    ]


def test_tool_calls_record_the_target_and_not_the_output(home):
    _write_transcript(
        home,
        [
            _claude_tool("Write", {"file_path": "/home/u/projects/etl/bronze.py"}),
            _claude_tool("Bash", {"command": "databricks jobs create --json @job.json"}),
            {
                "type": "user",
                "message": {
                    "role": "user",
                    "content": [
                        {"type": "tool_result", "content": "created job 12345\n" * 500}
                    ],
                },
            },
        ],
    )
    result = harvest_user(_User(str(home)))

    assert "Write /home/u/projects/etl/bronze.py" in result.tool_targets
    assert any("databricks jobs create" in t for t in result.tool_targets)
    assert not any("created job 12345" in t for t in result.tool_targets)


def test_repeated_tool_targets_are_deduped(home):
    _write_transcript(
        home,
        [_claude_tool("Read", {"file_path": "/home/u/projects/etl/bronze.py"})] * 20,
    )
    result = harvest_user(_User(str(home)))

    assert result.tool_targets == ["Read /home/u/projects/etl/bronze.py"]


def test_error_first_lines_are_captured_and_bodies_are_not(home):
    """The blocker is in the first line; the traceback is noise and risk."""
    _write_transcript(
        home,
        [
            _claude_user(
                [
                    {
                        "type": "tool_result",
                        "is_error": True,
                        "content": (
                            "PERMISSION_DENIED: User does not have CREATE TABLE on "
                            "schema main.sales\n"
                            "  File \"/usr/lib/python3/spark.py\", line 402, in run\n"
                            "    raise AnalysisException(msg)\n"
                        ),
                    }
                ]
            )
        ],
    )
    result = harvest_user(_User(str(home)))

    assert result.errors == [
        "PERMISSION_DENIED: User does not have CREATE TABLE on schema main.sales"
    ]
    assert not any("spark.py" in e for e in result.errors)


def test_repeated_errors_are_deduped(home):
    """One bad credential produces the same error all day."""
    entry = _claude_user(
        [{"type": "tool_result", "is_error": True, "content": "401 Unauthorized"}]
    )
    _write_transcript(home, [entry] * 50)
    result = harvest_user(_User(str(home)))

    assert result.errors == ["401 Unauthorized"]


def test_a_successful_tool_result_is_not_an_error(home):
    _write_transcript(
        home,
        [_claude_user([{"type": "tool_result", "content": "ok"}])],
    )
    assert harvest_user(_User(str(home))).errors == []


# --- Documents ----------------------------------------------------------------


def test_promote_docs_are_described_but_not_shipped(home):
    promote = home / "promote"
    promote.mkdir()
    (promote / "architecture.md").write_text("# Architecture\nKafka to Delta.\n")
    (promote / "jira-stories.md").write_text("# Epic\nBusiness value: fraud losses.\n")
    result = harvest_user(_User(str(home)))

    kinds = {(a.kind, a.title) for a in result.artifacts}
    assert ("promote_doc", "architecture.md") in kinds
    # Named for its content, not its filename markers — a marker list would have
    # dropped exactly the document that states business value.
    assert ("promote_doc", "jira-stories.md") in kinds
    assert all(a.bytes > 0 for a in result.artifacts)
    # Only kind/title/bytes leave the instance.
    assert set(result.artifact_payload()[0]) == {"kind", "title", "bytes"}


def test_document_excerpts_stay_local(home):
    """They feed the on-instance summariser; the wire carries metadata only."""
    promote = home / "promote"
    promote.mkdir()
    (promote / "architecture.md").write_text("They run Snowflake and want to migrate.")
    result = harvest_user(_User(str(home)))

    assert any("Snowflake" in excerpt for _, excerpt in result.documents)
    assert not any("Snowflake" in json.dumps(p) for p in result.artifact_payload())


def test_readmes_and_prds_in_projects_are_found(home):
    repo = home / "projects" / "fraud"
    (repo / "docs").mkdir(parents=True)
    (repo / "README.md").write_text("# Fraud scoring\n")
    (repo / "docs" / "prd.md").write_text("# PRD\n")
    (repo / "main.py").write_text("print('not a document')")
    result = harvest_user(_User(str(home)))

    kinds = {a.kind for a in result.artifacts}
    assert {"readme", "prd"} <= kinds
    assert not any(a.title.endswith(".py") for a in result.artifacts)


def test_document_contents_are_redacted_before_the_summariser_sees_them(home):
    promote = home / "promote"
    promote.mkdir()
    (promote / "security.md").write_text(f"Connect with {fake.PG_URL_PROD}")
    result = harvest_user(_User(str(home)))

    excerpt = result.documents[0][1]
    assert "hunter2" not in excerpt
    assert result.redactions >= 1


def test_dependency_trees_are_not_walked(home):
    """A node_modules checkout would otherwise turn this into a full-disk walk."""
    junk = home / "projects" / "app" / "node_modules" / "left-pad"
    junk.mkdir(parents=True)
    (junk / "README.md").write_text("# left-pad\n")
    result = harvest_user(_User(str(home)))

    assert result.artifacts == []


def test_shared_tmp_promote_is_ignored_on_a_shared_instance(tmp_path, monkeypatch):
    """/tmp is shared by uid, so trusting it could brief the wrong company.

    On the supported one-attendee topology it is the promote skill's historical
    output location and must be read; on a shared instance the same directory
    cannot be attributed to anyone.
    """
    shared = tmp_path / "tmp" / "promote"
    shared.mkdir(parents=True)
    (shared / "architecture.md").write_text("# Architecture\n")
    monkeypatch.setattr(
        artifacts, "_document_roots",
        lambda home, *, include_shared_tmp: (
            [str(shared)] if include_shared_tmp else []
        ),
    )
    home = tmp_path / "home"
    home.mkdir()

    alone = harvest_user(_User(str(home)), single_attendee=True)
    shared_instance = harvest_user(_User(str(home)), single_attendee=False)

    assert [a.title for a in alone.artifacts] == ["architecture.md"]
    assert shared_instance.artifacts == []


def test_the_real_root_list_includes_tmp_promote_only_when_alone(tmp_path):
    alone = artifacts._document_roots("/h", include_shared_tmp=True)
    shared = artifacts._document_roots("/h", include_shared_tmp=False)

    assert "/tmp/promote" in alone
    assert "/tmp/promote" not in shared
    assert "/h/promote" in shared


# --- Commit subjects ----------------------------------------------------------


def _git_repo(path, subjects):
    """A throwaway repo, isolated from the developer's global git config.

    Without the config isolation a machine with commit signing enabled blocks on
    a passphrase prompt and the suite hangs rather than fails.
    """
    path.mkdir(parents=True, exist_ok=True)
    env = {
        **os.environ,
        "GIT_CONFIG_GLOBAL": os.devnull,
        "GIT_CONFIG_SYSTEM": os.devnull,
        "GIT_AUTHOR_NAME": "A", "GIT_AUTHOR_EMAIL": "a@x.com",
        "GIT_COMMITTER_NAME": "A", "GIT_COMMITTER_EMAIL": "a@x.com",
    }
    run = lambda *args: subprocess.run(  # noqa: E731
        ["git", "-c", "commit.gpgsign=false", *args],
        cwd=path, check=True, env=env, capture_output=True, timeout=30,
    )
    run("init", "-q")
    for i, subject in enumerate(subjects):
        (path / f"f{i}.txt").write_text(subject)
        run("add", "-A")
        run("commit", "-q", "-m", subject)


def test_commit_subjects_are_captured(home):
    _git_repo(
        home / "projects" / "fraud",
        ["Add Kafka bronze ingest", "Score transactions with the served model"],
    )
    result = harvest_user(_User(str(home)))

    titles = {a.title for a in result.artifacts if a.kind == "commit"}
    assert "Add Kafka bronze ingest" in titles
    assert "Score transactions with the served model" in titles


def test_a_directory_without_git_is_skipped(home):
    plain = home / "projects" / "scratch"
    plain.mkdir(parents=True)
    (plain / "notes.txt").write_text("x")
    assert harvest_user(_User(str(home))).artifacts == []


def test_commits_cannot_crowd_out_documents(home):
    """The architecture doc is worth more than the fiftieth commit subject."""
    promote = home / "promote"
    promote.mkdir()
    (promote / "architecture.md").write_text("# Architecture\n")
    _git_repo(home / "projects" / "app", [f"commit {i}" for i in range(60)])
    result = harvest_user(_User(str(home)))

    commits = [a for a in result.artifacts if a.kind == "commit"]
    assert len(commits) == artifacts.MAX_COMMITS
    assert any(a.kind == "promote_doc" for a in result.artifacts)


# --- Failure behaviour --------------------------------------------------------


def test_an_empty_home_yields_an_empty_harvest(tmp_path):
    result = harvest_user(_User(str(tmp_path / "nonexistent")))

    assert result.is_empty()
    assert result.prompt_count == 0


def test_emptiness_is_reported_rather_than_invented(home):
    """A summary over nothing would be fabrication, so callers must be able to tell."""
    assert harvest_user(_User(str(home))).is_empty() is True
    _write_transcript(home, [_claude_user("what is unity catalog?")])
    assert harvest_user(_User(str(home))).is_empty() is False


def test_a_corrupt_transcript_line_does_not_lose_the_file(home):
    path = home / ".claude" / "projects" / "p" / "session.jsonl"
    path.write_text(
        "{not json\n"
        + json.dumps(_claude_user("real question about lakeflow"))
        + "\n"
        + "\x00\x01\n"
    )
    result = harvest_user(_User(str(home)))

    assert result.prompts == ["real question about lakeflow"]


def test_an_enormous_single_line_is_skipped_as_a_tool_dump(home):
    _write_transcript(
        home,
        [
            _claude_user("a" * (artifacts.MAX_LINE_BYTES + 10)),
            _claude_user("small real question"),
        ],
    )
    result = harvest_user(_User(str(home)))

    assert result.prompts == ["small real question"]


def test_a_harvest_never_raises(home, monkeypatch):
    """Both callers are best-effort paths where an exception costs something real."""
    monkeypatch.setattr(
        artifacts, "_scan_transcripts",
        lambda *a, **k: (_ for _ in ()).throw(RuntimeError("disk gone")),
    )
    assert isinstance(harvest_user(_User(str(home))), Harvest)


def test_artifact_payload_is_metadata_only():
    payload = Artifact(kind="promote_doc", title="architecture.md", bytes=4096).payload()
    assert payload == {"kind": "promote_doc", "title": "architecture.md", "bytes": 4096}
